name: WhatsApp Bot

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Set up virtual display
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb x11-xserver-utils
        # Create directory for X11 socket
        sudo mkdir -p /tmp/.X11-unix
        sudo chmod 1777 /tmp/.X11-unix
        # Start Xvfb with specific parameters
        Xvfb :99 -screen 0 1024x768x16 -ac &
        echo "DISPLAY=:99" >> $GITHUB_ENV
        # Wait for Xvfb to start
        sleep 3
        # Verify Xvfb is running
        ps aux | grep Xvfb

    - name: Run bot
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        MAX_TOKENS: 70
        MODEL: gpt-3.5-turbo
        DISPLAY: :99
      run: |
        # Verify DISPLAY environment variable
        echo "Display is set to: $DISPLAY"
        # Verify X11 socket exists
        ls -la /tmp/.X11-unix/
        # Run the bot
        python whatsapp_bot.py